/**
 * Sample-archive presets surfaced in the demo UI. Pure data.
 *
 * Each preset points at a synthetic many-file ZIP generated by
 * `scripts/make-sample.ts` and uploaded to the demo R2 bucket, fronted by a
 * public range-capable URL. `sizeBytes` is the REAL on-disk archive size (the
 * UI shows it as a human label). Until a sample is actually generated +
 * uploaded, its `url` is a documented placeholder — see the README.
 *
 * IMPORTANT: these are the ONLY built-in source URLs offered to the demo. They
 * must be hosts that honour HTTP range requests (R2 public buckets do).
 */

export interface SamplePreset {
  /** Stable id used in the UI + API. */
  readonly id: string;
  /** Human label, e.g. "Sample — 2 GB". */
  readonly label: string;
  /** Real archive size in bytes (shown formatted). */
  readonly sizeBytes: number;
  /** Approximate file count inside the archive (for the UI blurb). */
  readonly fileCount: number;
  /** Public, range-capable URL of the archive. PLACEHOLDER until uploaded. */
  readonly url: string;
  /** True once the URL points at a real uploaded object (vs a placeholder). */
  readonly available: boolean;
}

/**
 * The presets. `sizeBytes` / `fileCount` are the REAL on-disk values measured
 * after each archive was built + uploaded to the `rangezip-samples` bucket.
 * The 2 GB sample holds 510 genuinely-distinct real files (ImageMagick plasma
 * images, ffmpeg MP4s, pdf-lib PDFs, real text/markdown/csv/json). The 10 GB
 * and 30 GB samples are built by CYCLING through the 2 GB sample's entries and
 * copying each entry's data VERBATIM into a new ZIP64 entry (unique renumbered
 * name, same method/sizes/CRC) — so every extracted file is a real, intact,
 * openable file, not synthetic filler, including entries well past the 4 GB
 * ZIP64 boundary. Each archive is verified before upload by re-parsing it with
 * this repo's own `src/zip` reader (CRC match + file-signature check).
 */
export const SAMPLE_PRESETS: readonly SamplePreset[] = [
  {
    id: 'sample-2gb',
    label: 'Sample — 2 GB (images · video · docs · text)',
    sizeBytes: 1951670880,
    fileCount: 510,
    url: 'https://rangezip-samples.grunt.si/sample-2gb.zip',
    available: true,
  },
  {
    id: 'sample-10gb',
    label: 'Sample — 10 GB (images · video · docs · text)',
    sizeBytes: 10743662171,
    fileCount: 2600,
    url: 'https://rangezip-samples.grunt.si/sample-10gb.zip',
    available: true,
  },
  {
    id: 'sample-30gb',
    label: 'Sample — 30 GB (images · video · docs · text)',
    sizeBytes: 32232826635,
    fileCount: 8211,
    url: 'https://rangezip-samples.grunt.si/sample-30gb.zip',
    available: true,
  },
];

/** Look up a preset by id. */
export function findSample(id: string): SamplePreset | undefined {
  return SAMPLE_PRESETS.find((s) => s.id === id);
}
