/**
 * Sample-archive presets surfaced in the demo UI. Pure data.
 *
 * Each preset points at a synthetic many-file ZIP generated by
 * `scripts/make-sample.ts` and uploaded to the demo R2 bucket, fronted by a
 * public range-capable URL. `sizeBytes` is the REAL on-disk archive size (the
 * UI shows it as a human label). Until a sample is actually generated +
 * uploaded, its `url` is a documented placeholder — see the README.
 *
 * IMPORTANT: these are the ONLY built-in source URLs offered to the demo. They
 * must be hosts that honour HTTP range requests (R2 public buckets do).
 */

export interface SamplePreset {
  /** Stable id used in the UI + API. */
  readonly id: string;
  /** Human label, e.g. "Sample — 2 GB". */
  readonly label: string;
  /** Real archive size in bytes (shown formatted). */
  readonly sizeBytes: number;
  /** Approximate file count inside the archive (for the UI blurb). */
  readonly fileCount: number;
  /** Public, range-capable URL of the archive. PLACEHOLDER until uploaded. */
  readonly url: string;
  /** True once the URL points at a real uploaded object (vs a placeholder). */
  readonly available: boolean;
}

const GB = 1024 * 1024 * 1024;

/**
 * The presets. Replace `url` with the real public R2 URL after running
 * `bun run scripts/make-sample.ts` and uploading (and flip `available`).
 */
export const SAMPLE_PRESETS: readonly SamplePreset[] = [
  {
    id: 'sample-2gb',
    label: 'Sample — 2 GB (images · video · docs · text)',
    sizeBytes: 1951670880,
    fileCount: 510,
    url: 'https://pub-433f90b13bb14e348dee6b9c4b019671.r2.dev/sample-2gb.zip',
    available: true,
  },
  {
    id: 'sample-10gb',
    label: 'Sample — 10 GB',
    sizeBytes: 10 * GB,
    fileCount: 10000,
    url: 'https://REPLACE-ME.r2.dev/samples/rangezip-sample-10gb.zip',
    available: false,
  },
  {
    id: 'sample-30gb',
    label: 'Sample — 30 GB',
    sizeBytes: 30 * GB,
    fileCount: 30000,
    url: 'https://REPLACE-ME.r2.dev/samples/rangezip-sample-30gb.zip',
    available: false,
  },
];

/** Look up a preset by id. */
export function findSample(id: string): SamplePreset | undefined {
  return SAMPLE_PRESETS.find((s) => s.id === id);
}
